=== qafedev/qafe-platform/qafe-core/src/main/resources/application-statements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://qafe.com/schema" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://qafe.com/schema" elementFormDefault="qualified">
	<xs:annotation>
	<xs:documentation>

				DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

				Copyright 2006- 2010 Qualogy B.V.. All rights reserved.

				The contents of this file are subject to the terms that are provided by
				Qualogy B.V. The file may not be copied or (re)distributed without
				the explicit written permission from Qualogy B.V.
				
				For more information visit http://www.qafe.com
                     
      
    		</xs:documentation>
    </xs:annotation>	
	<xs:element name="statements" type="statementsType">
		<xs:annotation>
			<xs:documentation>The container for the several kinds of statements tags (insert, update,delete, etc).</xs:documentation>
		</xs:annotation></xs:element>
	<xs:complexType name="queryType"  mixed="true">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:string" use="required"/>
				<xs:attribute name="order" type="xs:string" use="optional"/>
				<xs:attribute name="sql" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="sqlQueryType">
		<xs:annotation>
			<xs:documentation>Either set the table attribute for generated query based upon table name and in out parameters or the sql attibute for handwritten sql or write inline sql which can be surrounded with CDATA</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="queryType">
				<xs:attribute name="table" type="xs:string"/>				
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="statementsType">
        <xs:annotation>
        	<xs:documentation>The super type of the supported statements</xs:documentation>
        </xs:annotation>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="batch" type="batchType"/>
			<xs:element name="call" type="callType"/>
			<xs:element name="query" type="simpleQueryType"/>
			<xs:element name="delete" type="deleteType"/>
			<xs:element name="select" type="selectType"/>
			<xs:element name="update" type="updateType"/>
			<xs:element name="insert" type="insertType"/>
		</xs:choice>
	</xs:complexType>
	<!-- regular -->
	<xs:complexType name="updateType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for update statements.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryType">
				<xs:attribute name="where" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="selectType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for select statements.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="insertType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for insert statements.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="deleteType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for delete statements.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryType">
				<xs:attribute name="where" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="simpleQueryType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for any type of sql query statement, free format, validation is done by the database.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="callType">
		<xs:simpleContent>
			<xs:extension base="queryType">
				<xs:attribute name="call-name" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!-- batch -->
	<xs:complexType name="updateBatchType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for update statements.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryBatchType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="selectBatchType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for select statements.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryBatchType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="insertBatchType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for insert statements.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryBatchType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="deleteBatchType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for delete statements.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryBatchType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="simpleQueryBatchType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. Tag for any type of sql query statement, free format, validation is done by the database.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="sqlQueryBatchType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="callBatchType">
		<xs:simpleContent>
			<xs:extension base="queryBatchType">
				<xs:attribute name="call-name" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="queryBatchType" abstract="true">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="ref" type="xs:string" use="optional"/>
				<xs:attribute name="order" type="xs:string" use="optional"/>
				<xs:attribute name="sql" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="batchBatchType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. A Batch can contain all statements specified. Batch statements will be executed according to their order attribute or the order Qafe reads the statements (assumably top down)</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="statementsBatchType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="sqlQueryBatchType">
		<xs:annotation>
			<xs:documentation>Either set the table attribute for generated query based upon table name and in out parameters or the sql attibute for handwritten sql or write inline sql which can be surrounded with CDATA</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="queryBatchType">
				<xs:attribute name="table" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="statementsBatchType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="batch" type="batchBatchType"/>
			<xs:element name="call" type="callBatchType"/>
			<xs:element name="query" type="simpleQueryBatchType"/>
			<xs:element name="delete" type="deleteBatchType"/>
			<xs:element name="select" type="selectBatchType"/>
			<xs:element name="update" type="updateBatchType"/>
			<xs:element name="insert" type="insertBatchType"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="batchType">
		<xs:annotation>
			<xs:documentation>See super type for attribute options. A Batch can contain all statements specified. Batch statements will be executed according to their order attribute or the order Qafe reads the statements (assumably top down)</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="statementsBatchType">
				<xs:attribute name="id" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== qafedev/qafe-platform/qafe-business/src/test/resources/test/com/qualogy/qafe/business/integration/rdb/conflictdetection/statements.xml
<?xml version="1.0"?>
<!--

    Copyright 2008-2017 Qualogy Solutions B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    	http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<statements xmlns="http://qafe.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://qafe.com/schema http://www.qafe.com/schema/application-statements.xsd">

	<batch id="setUp">
		<query sql="delete from QAFE_TEST_SELECTDB" />
		<query sql="insert into QAFE_TEST_SELECTDB values ('E1','Binu','D1',to_date('10-12-1980','MM-DD-YYYY'),'2')" />
		<query sql="insert into QAFE_TEST_SELECTDB values ('E2','Hallo','D1',to_date('08-12-1982','MM-DD-YYYY'),'1')" />
	</batch>

	<select id="selectConflict1" table="QAFE_TEST_SELECTDB" />
	<select id="selectConflict2" sql="select * from QAFE_TEST_SELECTDB" />
	<select id="selectConflict3" sql="select EMP_ID, EMP_NAME, CHILDREN from QAFE_TEST_SELECTDB" />
	<select id="selectConflict4" sql="select EMP_ID as EMPID, EMP_NAME EMPNAME, CHILDREN from QAFE_TEST_SELECTDB" />

	<update id="updateConflict1" table="QAFE_TEST_SELECTDB" where="EMP_ID=:EMP_ID"/>
	<update id="updateConflict2" sql="update QAFE_TEST_SELECTDB set EMP_NAME=:EMP_NAME, CHILDREN=:CHILDREN where EMP_ID=:EMP_ID" />
	<update id="updateConflict4" sql="update QAFE_TEST_SELECTDB set EMP_NAME=:EMPNAME, CHILDREN=:CHILDREN where EMP_ID=:EMPID" />

	<delete id="deleteConflict1" sql="delete from QAFE_TEST_SELECTDB where EMP_ID=:pk"/>

</statements>

=== qafedev/qafe-platform/qafe-business/src/test/resources/test/com/qualogy/qafe/business/integration/rdb/update/statements.xml
<?xml version="1.0"?>
<!--

    Copyright 2008-2017 Qualogy Solutions B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    	http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<statements xmlns="http://qafe.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://qafe.com/schema http://www.qafe.com/schema/application-statements.xsd">
		
	<batch id="insertData">
		<query>insert into QAFE_TEST_UPDATE (ID, NAME, ADDRESS, EMAIL, SALARY) values (1, 'A', 'A1' , 'a@a.com', 1000)</query>
		<query>insert into QAFE_TEST_UPDATE (ID, NAME, ADDRESS, EMAIL, SALARY) values (2, 'B', 'B2' , 'b@b.com', 2000)</query>
		<query>insert into QAFE_TEST_UPDATE (ID, NAME, ADDRESS, EMAIL, SALARY) values (3, 'C', 'C3' , 'c@c.com', 3000)</query>
		<query>insert into QAFE_TEST_UPDATE (ID, NAME, ADDRESS, EMAIL, SALARY) values (4, 'D', 'D4' , 'd@d.com', 4000)</query>
	</batch>
	
	<query id="selectOne">select * from QAFE_TEST_UPDATE where ID = 1</query>
	
	<query id="selectAll">select * from QAFE_TEST_UPDATE order by ID</query>
	
	<update id="useUpdateTagWithTableName" table="QAFE_TEST_UPDATE"/>
	
	<update id="updateWithSqlAttribute" sql="update QAFE_TEST_UPDATE set NAME='Bob' where ID=1"/>
	
	<update id="updateWithSqlAttributeAndInParams" sql="update QAFE_TEST_UPDATE set NAME=:nameVar, SALARY=:salaryVar, ENTRY_DATE=:dateVar where ID=:idVar"/>
	
	<update id="updateWithSqlAsText">update QAFE_TEST_UPDATE set NAME='Amanda', SALARY=8000 where ID=1</update> <!-- Double quotes are replaced to single quotes before executing. -->
	
	<update id="updateWithSqlAsTextAndInParams">update QAFE_TEST_UPDATE set NAME=:nameVar, SALARY=:salaryVar where ID=:idVar</update>
	
	<update id="updateWithAllAttributes" table="IGNORED" sql="update QAFE_TEST_UPDATE set ADDRESS=:addressVar where ID=:idVar" where="IGNORED"/>

	<update id="updateWithTableAndSqlAttribute" table="IGNORED" sql="update QAFE_TEST_UPDATE set ADDRESS=:addressVar, SALARY=:salaryVar where ID=:idVar"/>
	
	<update id="updateWithSqlAndWhereAttribute" sql="update QAFE_TEST_UPDATE set NAME=:nameVar, ENTRY_DATE=:dateVar where ID=:idVar" where="IGNORED"/>
	
	<update id="updateWithSqlAttributeAndSqlText" sql="update QAFE_TEST_UPDATE set ENTRY_DATE=:dateVar where ID=:idVar">IGNORED</update>
	
	<update id="updateWithTableAndWhereAttribute" table="QAFE_TEST_UPDATE" where="ID > :ID and ADDRESS=:ADDRESS"/>
	
	<update id="updateWithSQLTextUsingCDATA"><![CDATA[update QAFE_TEST_UPDATE 
														 set NAME=:nameVar, SALARY=:salaryVar 
													   where ID > :minIdVar and ID < :maxIdVar]]></update>
	
	<query id="deleteData">delete from QAFE_TEST_UPDATE</query>
		
</statements>

=== qafedev/qafe-platform/qafe-business/src/test/resources/test/com/qualogy/qafe/business/integration/rdb/delete/statements.xml
<?xml version="1.0"?>
<!--

    Copyright 2008-2017 Qualogy Solutions B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    	http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<statements xmlns="http://qafe.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://qafe.com/schema http://www.qafe.com/schema/application-statements.xsd">
	
	<!-- <insert sql="into users (id, name, birthdate) values('0', 'A', '18-08-1978')"/>
	<insert id="testInsertWithQuestionmarks" sql="into users (id, name, birthdate) values(?,?,?)"/> 
	-->
	<batch id="setup">
		<query sql="delete from QAFE_TEST_DELETE"></query>
	</batch>
	<batch id="teardown">
		<query sql="delete from QAFE_TEST_DELETE"></query>		
	</batch>
	<batch id="insertTestDataSet1">
		<query sql="insert into QAFE_TEST_DELETE(EMP_ID,EMP_NAME,DEP_ID) values('E1','E1Name','D1') "></query>
		<query sql="insert into QAFE_TEST_DELETE(EMP_ID,EMP_NAME,DEP_ID) values('E2','E2Name','D1') "></query>
		<query sql="insert into QAFE_TEST_DELETE(EMP_ID,EMP_NAME,DEP_ID) values('E3','E3Name','D2') "></query>
	</batch>
	<batch id="insertTestDataSet2">
		<query sql="insert into QAFE_TEST_DELETE(EMP_ID,EMP_NAME,DEP_ID) values('E1','E1Name','D1') "></query>
		<query sql="insert into QAFE_TEST_DELETE(EMP_ID,EMP_NAME,DEP_ID) values('E2','E2Name','D1') "></query>
	</batch>
			
	<delete id="testDeletePassingTableNameOnly" table="QAFE_TEST_DELETE"/>
	<delete id="testDeletePassingWrongTableName" table="NOT_EXISTING_TABLE"/>
	<delete id="deleteWithWhere" table="QAFE_TEST_DELETE" where="dep_Id=:dep_Id"/> 
	<delete id="deleteWithWhereAndSQLAttribute" sql="delete from QAFE_TEST_DELETE" where="dep_Id=:dep_Id"/>
	
	
	<query id="getData" sql="select EMP_ID,EMP_NAME,DEP_ID from QAFE_TEST_DELETE"/>
	
</statements>

=== qafedev/qafe-platform/qafe-business/src/test/resources/test/com/qualogy/qafe/business/integration/rdb/insert/statements.xml
<?xml version="1.0"?>
<!--

    Copyright 2008-2017 Qualogy Solutions B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    	http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<statements xmlns="http://qafe.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://qafe.com/schema http://www.qafe.com/schema/application-statements.xsd">
	
	<batch id="setup">
		<query sql="delete from QAFE_TEST_INSERT"></query>
	</batch>
	<batch id="teardown">
		<query sql="delete from QAFE_TEST_INSERT"></query>		
	</batch>
	
	<query id="getData" sql="select EMP_ID,EMP_NAME,DEP_ID,SALARY,ENTRY_DATE from QAFE_TEST_INSERT"/>
		
	<insert id="testInsertPassingTableNameWithInputsFormService" table="QAFE_TEST_INSERT"></insert>
 	<insert id="testInsertPassingSqlAttributeWithInputsFormService" sql="insert into QAFE_TEST_INSERT(EMP_ID,EMP_NAME,DEP_ID,SALARY,ENTRY_DATE) values(:EMP_ID,:EMP_NAME,:DEP_ID,:SALARY,:ENTRY_DATE)"></insert>
 	<insert id="testInsertPassingSqlAsTextWithInputsFormService">insert into QAFE_TEST_INSERT(EMP_ID,EMP_NAME,DEP_ID,SALARY,ENTRY_DATE) values(:EMP_ID,:EMP_NAME,:DEP_ID,:SALARY,:ENTRY_DATE)</insert>
 	<insert id="testInsertPassingCDataSqlAsTextWithInputsFormService"><![CDATA[insert into QAFE_TEST_INSERT(EMP_ID,EMP_NAME,DEP_ID,SALARY,ENTRY_DATE) values(:EMP_ID,:EMP_NAME,:DEP_ID,:SALARY,:ENTRY_DATE)]]></insert>
 
</statements>

=== qafedev/qafe-platform/qafe-business/src/test/resources/samples/businessactionmanager/statement.xml
<?xml version="1.0"?>
<!--

    Copyright 2008-2017 Qualogy Solutions B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    	http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<statements xmlns="http://qafe.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://qafe.com/schema http://www.qafe.com/schema/application-statements.xsd">
	<batch id="setup">
		<query sql="create table users (id VARCHAR, name VARCHAR)"/><!-- other type -->
		<query sql="ALTER TABLE users ADD CONSTRAINT PK PRIMARY KEY (id)"/><!-- other type -->
		<insert sql="insert into users (id, name) values('1', 'marc')"/>
	</batch>
	<batch id="teardown">
		<query sql="drop table users"/>
	</batch>
	<select id="select_all" sql="select * from users"/>	

	<insert id="insert_user" sql="insert into users (id, name) values(:id, :name)"/>

	<insert id="insertuseralreadyexists" sql="insert into users (id, name) values('1', 'marc')"/>
	
	<select id="testSelectSQLAsAttribute" sql="select * from users where id=:id "/>
	
	<select id="testSelectSQLAsText">
		select * from users where id=:id
	</select>
	<select id="testSelectSQLAsTextUseIn">
		select * from users
	</select>
	<select id="testSelectSQLAsTextUseOut">
		select * from users where id=:id
	</select>
	<select id="testSelectSQLAsTextUseInAndOut">
		select * from users
	</select>
	<select id="testSelectSQLUseInAndOutAndTableName" table="users"/>
</statements>

=== qafedev/qafe-platform/qafe-business/src/test/resources/test/com/qualogy/qafe/business/integration/rdb/call/call-statements.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Copyright 2008-2017 Qualogy Solutions B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    	http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<statements xmlns="http://qafe.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://qafe.com/schema http://www.qafe.com/schema/application-statements.xsd">
	
	
	<call id="callWithObjectOutput" sql="{call QAFE_COMPLEX_DATA.GetValuesObj(?)}" ></call>
	<call id="callWithObjectInput" sql="{call QAFE_COMPLEX_DATA.PutValuesObj(?,?)}" ></call>
	
	
	<call id="getFuncHello" call-name="qpd_fnc_get_hello" ></call>
	
	<call id="getFuncName" call-name="qpd_fnc_get_ename" ></call>
	<call id="getProcName" call-name="qpd_prc_get_ename" ></call>
	
	<call id="getFuncNameBySQL" sql="{? = call qpd_fnc_get_ename(?)}" ></call>
	<call id="getProcNameBySQL" sql="{call qpd_prc_get_ename(?,?)}" ></call>
	
	<call id="getPackFuncName" call-name="QPD_TEST_PCK.get_ename_fnc" ></call>
	<call id="getPackProcName" call-name="QPD_TEST_PCK.get_ename_prc" ></call>
	
	<call id="getPackFuncNameBySQL" sql="{? = call QPD_TEST_PCK.get_ename_fnc(?)}" ></call>
	<call id="getPackProcNameBySQL" sql="{call QPD_TEST_PCK.get_ename_prc(?,?)}" ></call>

 	<call id="getFuncNameBySQLAndNamedVars" sql="{? = call qpd_fnc_get_ename(:p_empno)}" ></call>
 	<call id="getProcNameBySQLAndNamedVars" sql="{call qpd_prc_get_ename(:p_empno,:p_ename)}" ></call>

	<call id="getPackFuncNameBySQLAndNamedVars" sql="{? = call QPD_TEST_PCK.get_ename_fnc(:p_empno)}" ></call>
	<call id="getPackProcNameBySQLAndNamedVars" sql="{call QPD_TEST_PCK.get_ename_prc(:p_empno,:p_ename)}" ></call>
	
	<call id="callSAY_HELLO_FNCOfQAFE_TESTS" sql="{? = call QAFE_TESTS.SAY_HELLO_FNC(:P_NAME)}"/>
	<call id="callSAY_HELLO_PRCOfQAFE_TESTS" sql="{call QAFE_TESTS.SAY_HELLO_PRC(:P_NAME,:P_RESULT)}"/>
	
	<!-- Calls in another schema -->
	<!-- In order to execute the call you need to do the following: grant EXECUTE on "QAFE"."QAFE_TESTS" to "HDEMO65"; -->
	<call id="callSAY_HELLO_FNCOfQAFE_TESTSOfAnotherSchema" sql="{? = call QAFE.QAFE_TESTS.SAY_HELLO_FNC(:P_NAME)}"/>
	<call id="callSAY_HELLO_PRCOfQAFE_TESTSOfAnotherSchema" sql="{call QAFE.QAFE_TESTS.SAY_HELLO_PRC(:P_NAME,:P_RESULT)}"/>
</statements>

=== qafedev/qafe-platform/qafe-core/src/test/resources/samples/statements/statements.xml
<?xml version="1.0"?>
<!--

    Copyright 2008-2017 Qualogy Solutions B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    	http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<statements xmlns="http://qafe.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://qafe.com/schema http://www.qafe.com/schema/application-statements.xsd">
	<batch id="setup">
		<query sql="create table users (id VARCHAR PRIMARY KEY, name VARCHAR, birthdate DATE)"/><!-- other type -->
		<!--<query sql="ALTER TABLE users ADD CONSTRAINT PK PRIMARY KEY (id)"/> -->
		<insert sql="into users (id, name, birthdate) values('0', 'marc', '18-08-1978')"/>
		<insert sql="into users (id, name) values('2', 'marc')"/>
		<insert sql="into users (id, name) values('3', 'marc')"/>
		<insert sql="into users (id, name) values('4', 'marc')"/>
		<insert sql="into users (id, name) values('5', 'marc')"/>
		<insert sql="into users (id, name) values('6', 'marc')"/>
		<insert sql="into users (id, name) values('7', 'marc')"/>
		<insert sql="into users (id, name) values('8', 'marc8')"/>
		<insert sql="into users (id, name) values('9', 'marc')"/>
		<insert sql="into users (id, name) values('1', 'marc')"/>
		<select ref="testGeneratedUpdate"/>
	</batch>
	<batch id="teardown">
		<query sql="drop table users"/>
	</batch>
	<select id="getUsersOrderdById" sql="select * from users order by id"/>
	<select id="getUsersById" table="users"/>
	<update id="testGeneratedUpdate" table="users"/>
</statements>

=== qafedev/qafe-platform/qafe-business/src/test/resources/test/com/qualogy/qafe/business/integration/rdb/query/statements.xml
<?xml version="1.0"?>
<!--

    Copyright 2008-2017 Qualogy Solutions B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    	http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<statements xmlns="http://qafe.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://qafe.com/schema http://www.qafe.com/schema/application-statements.xsd">
	<batch id="setup">
		<query sql="create table qafe_test_query (id VARCHAR PRIMARY KEY, name VARCHAR)"/>
		<!--<query sql="ALTER TABLE users ADD CONSTRAINT PK PRIMARY KEY (id)"/> -->
		<insert sql="insert into qafe_test_query (id, name) values('0', 'A')"/>
		<insert sql="insert into qafe_test_query (id, name) values('2', 'C')"/>
		<insert sql="insert into qafe_test_query (id, name) values('3', 'marc')"/>
		<insert sql="insert into qafe_test_query (id, name) values('4', 'D')"/>
		<insert sql="insert into qafe_test_query (id, name) values('5', 'marc')"/>
		<insert sql="insert into qafe_test_query (id, name) values('6', 'marc')"/>
		<insert sql="insert into qafe_test_query (id, name) values('7', 'marc')"/>
		<insert sql="insert into qafe_test_query (id, name) values('8', 'marc8')"/>
		<insert sql="insert into qafe_test_query (id, name) values('9', 'Z')"/>
		<insert sql="insert into qafe_test_query (id, name) values('1', 'B')"/>
	</batch>
	<batch id="teardown">
		<query sql="drop table qafe_test_query"/>
	</batch>
	<query id="getUsersSqlAsAttribute" sql="select * from qafe_test_query"/>
	<query id="getUsersSqlAsText">select * from qafe_test_query</query>	
	<query id="getUsersSqlAsAttributeById" sql="select * from qafe_test_query where id=:id"/>	
	<query id="getUsersSqlAsTextById">select * from qafe_test_query where id=:id</query>	
	
</statements>
